'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Package, WarningCircle } from '@phosphor-icons/react'
import Navbar from '@/components/Navbar'
import { createClient } from '@/utils/supabase/client'

type Row={id:string;product_id:string;product_name:string;quantity:number;reserved_quantity:number;low_stock_threshold:number;status:string}
export default function SellerInventoryPage(){const[rows,setRows]=useState<Row[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[busy,setBusy]=useState('')
async function load(){const s=createClient();const{data:a}=await s.auth.getUser();if(!a.user){window.location.replace('/login?next=/commerce/seller/inventory');return};const{data:v}=await s.from('vendor_profiles').select('id,status').eq('user_id',a.user.id).maybeSingle();if(!v||v.status!=='approved'){window.location.replace('/commerce/seller');return};const{data:p,error:e}=await s.from('products').select('id,name_bn,name_en,status,inventory(quantity,reserved_quantity,low_stock_threshold)').eq('vendor_id',v.id).order('created_at',{ascending:false});if(e){setError('Inventory load করা যায়নি।');setLoading(false);return};setRows((p??[]).map((x:any)=>({id:x.id,product_id:x.id,product_name:x.name_bn||x.name_en,quantity:Number(x.inventory?.quantity??0),reserved_quantity:Number(x.inventory?.reserved_quantity??0),low_stock_threshold:Number(x.inventory?.low_stock_threshold??5),status:x.status})));setLoading(false)}
useEffect(()=>{void load()},[])
async function save(row:Row){setBusy(row.id);setError('');const s=createClient();const{error:e}=await s.rpc('set_vendor_product_inventory',{p_product_id:row.product_id,p_quantity:row.quantity,p_low_stock_threshold:row.low_stock_threshold});if(e)setError('Inventory update করা যায়নি।');else await load();setBusy('')}
return <main className="min-h-screen bg-[#f7faf9] text-[#0b1736] dark:bg-[#030506] dark:text-white"><Navbar/><section className="mx-auto max-w-6xl px-4 pb-20 pt-8 sm:px-6 lg:px-8"><Link href="/commerce/seller" className="inline-flex items-center gap-2 rounded-xl border border-[#0b1736]/10 bg-white/70 px-3.5 py-2 text-sm dark:border-white/10 dark:bg-white/[.045]"><ArrowLeft size={17}/> Seller Dashboard</Link><div className="mt-9"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#008080]">Inventory</p><h1 className="mt-2 text-4xl font-black">Stock management</h1><p className="mt-2 text-sm opacity-55">Stock mutation database RPC দিয়ে protected।</p></div>{error&&<div className="mt-6 rounded-xl bg-red-500/5 p-4 text-sm text-red-600">{error}</div>}{loading?<div className="py-24 text-center opacity-50">Inventory loading...</div>:rows.length?<div className="mt-8 grid gap-4">{rows.map(r=>{const available=Math.max(r.quantity-r.reserved_quantity,0);const low=available<=r.low_stock_threshold;return <div key={r.id} className="rounded-2xl border border-[#0b1736]/10 bg-white/80 p-5 dark:border-white/10 dark:bg-white/[.045]"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><p className="font-black">{r.product_name}</p><p className="mt-1 text-xs opacity-45">{r.status} · reserved {r.reserved_quantity} · available {available}</p></div><div className="flex flex-wrap items-end gap-3"><label className="text-xs font-bold">Quantity<input type="number" min="0" max="100000000" value={r.quantity} onChange={e=>setRows(xs=>xs.map(x=>x.id===r.id?{...x,quantity:Math.max(0,Number(e.target.value))}:x))} className="mt-1 h-11 w-32 rounded-xl border border-[#0b1736]/10 bg-transparent px-3 dark:border-white/10"/></label><label className="text-xs font-bold">Low stock<input type="number" min="0" max="100000000" value={r.low_stock_threshold} onChange={e=>setRows(xs=>xs.map(x=>x.id===r.id?{...x,low_stock_threshold:Math.max(0,Number(e.target.value))}:x))} className="mt-1 h-11 w-32 rounded-xl border border-[#0b1736]/10 bg-transparent px-3 dark:border-white/10"/></label><button disabled={busy===r.id} onClick={()=>void save(r)} className="h-11 rounded-xl bg-[#008080] px-4 text-sm font-bold text-white disabled:opacity-40">{busy===r.id?'Saving…':'Save'}</button></div></div>{low&&<p className="mt-4 flex items-center gap-2 text-xs font-semibold text-[#8c6a0e]"><WarningCircle size={15}/> Low stock alert</p>}</div>})}</div>:<div className="mt-8 rounded-2xl p-10 text-center opacity-50"><Package size={40} className="mx-auto"/>No products yet.</div>}</section></main>}
