'use client'

import { FormEvent, useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Storefront } from '@phosphor-icons/react'
import Navbar from '@/components/Navbar'
import { createClient } from '@/utils/supabase/client'

type Vendor={display_name:string;display_name_bn:string|null;display_name_en:string|null;description_bn:string|null;description_en:string|null;phone:string|null;shop_slug:string|null;status:string;is_verified:boolean}
export default function SellerSettingsPage(){const[v,setV]=useState<Vendor|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('')
useEffect(()=>{async function load(){const s=createClient();const{data:a}=await s.auth.getUser();if(!a.user){window.location.replace('/login?next=/commerce/seller/settings');return};const{data,error:e}=await s.from('vendor_profiles').select('display_name,display_name_bn,display_name_en,description_bn,description_en,phone,shop_slug,status,is_verified').eq('user_id',a.user.id).maybeSingle();if(e||!data){window.location.replace('/commerce/seller');return};setV(data as Vendor);setLoading(false)}void load()},[])
async function submit(e:FormEvent){e.preventDefault();if(!v)return;setSaving(true);setMessage('');setError('');const s=createClient();const{error:e2}=await s.rpc('update_vendor_profile',{p_display_name:v.display_name,p_display_name_bn:v.display_name_bn,p_display_name_en:v.display_name_en,p_description_bn:v.description_bn,p_description_en:v.description_en,p_phone:v.phone,p_shop_slug:v.shop_slug});if(e2)setError('Settings save করা যায়নি। Shop slug unique এবং valid হতে হবে।');else setMessage('Seller profile updated successfully.');setSaving(false)}
if(loading)return <main className="min-h-screen bg-[#f7faf9] dark:bg-[#030506]"><Navbar/><div className="flex min-h-[70vh] items-center justify-center opacity-50">Loading...</div></main>
return <main className="min-h-screen bg-[#f7faf9] text-[#0b1736] dark:bg-[#030506] dark:text-white"><Navbar/><section className="mx-auto max-w-4xl px-4 pb-20 pt-8 sm:px-6 lg:px-8"><Link href="/commerce/seller" className="inline-flex items-center gap-2 rounded-xl border border-[#0b1736]/10 bg-white/70 px-3.5 py-2 text-sm dark:border-white/10 dark:bg-white/[.045]"><ArrowLeft size={17}/> Seller Dashboard</Link><div className="mt-9 flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#008080]/10 text-[#008080]"><Storefront size={24}/></div><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#008080]">Seller Settings</p><h1 className="mt-1 text-4xl font-black">Store profile</h1></div></div><form onSubmit={submit} className="mt-8 rounded-[2rem] border border-[#0b1736]/10 bg-white/80 p-6 dark:border-white/10 dark:bg-white/[.045] sm:p-8">{error&&<div className="mb-5 rounded-xl bg-red-500/5 p-4 text-sm text-red-600">{error}</div>}{message&&<div className="mb-5 rounded-xl bg-[#008080]/5 p-4 text-sm text-[#007373]">{message}</div>}<div className="grid gap-5 sm:grid-cols-2"><Field label="Store name" value={v!.display_name} set={x=>setV({...v!,display_name:x})}/><Field label="Shop slug" value={v!.shop_slug||''} set={x=>setV({...v!,shop_slug:x.toLowerCase().replace(/[^a-z0-9-]/g,'-')})}/><Field label="Bangla name" value={v!.display_name_bn||''} set={x=>setV({...v!,display_name_bn:x})}/><Field label="English name" value={v!.display_name_en||''} set={x=>setV({...v!,display_name_en:x})}/><Field label="Phone" value={v!.phone||''} set={x=>setV({...v!,phone:x})}/></div><Text label="Bangla description" value={v!.description_bn||''} set={x=>setV({...v!,description_bn:x})}/><Text label="English description" value={v!.description_en||''} set={x=>setV({...v!,description_en:x})}/><button disabled={saving} className="mt-6 rounded-xl bg-[#008080] px-5 py-3 text-sm font-bold text-white disabled:opacity-40">{saving?'Saving…':'Save store profile'}</button></form></section></main>}
function Field({label,value,set}:{label:string;value:string;set:(x:string)=>void}){return <label className="text-sm font-semibold">{label}<input value={value} onChange={e=>set(e.target.value.slice(0,200))} className="mt-2 h-12 w-full rounded-xl border border-[#0b1736]/10 bg-transparent px-4 outline-none focus:border-[#008080] dark:border-white/10"/></label>}
function Text({label,value,set}:{label:string;value:string;set:(x:string)=>void}){return <label className="mt-5 block text-sm font-semibold">{label}<textarea value={value} onChange={e=>set(e.target.value.slice(0,4000))} className="mt-2 min-h-28 w-full rounded-xl border border-[#0b1736]/10 bg-transparent px-4 py-3 outline-none focus:border-[#008080] dark:border-white/10"/></label>}
