'use client'

import Link from 'next/link'
import { useCallback, useEffect, useState } from 'react'
import { ArrowLeft, BookmarkSimple, ChatCircle, PaperPlaneRight, ShareNetwork, ThumbsUp, Trash, UserCircle } from '@phosphor-icons/react'
import Navbar from '@/components/Navbar'
import { createClient } from '@/utils/supabase/client'
import { useFenixLocale } from '@/components/i18n/FenixLocaleProvider'

type Answer={id:string;body:string;created_at:string;updated_at:string;author_id:string;author_name:string|null;author_username:string|null;author_avatar_url:string|null;score:number}
type Question={id:string;title:string;body:string;created_at:string;author_id:string;author_name:string|null;author_username:string|null;author_avatar_url:string|null;topic_id:string|null;topic_name:string|null}

export default function QuestionPage({params}:{params:{id:string}}){
 const {locale}=useFenixLocale(); const [q,setQ]=useState<Question|null>(null); const [answers,setAnswers]=useState<Answer[]>([]); const [userId,setUserId]=useState<string|null>(null); const [body,setBody]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('')
 const load=useCallback(async()=>{const s=createClient();const [{data:auth},{data:qv},{data:av}]=await Promise.all([s.auth.getUser(),s.from('fenix_public_question_feed').select('*').eq('id',params.id).maybeSingle(),s.from('fenix_public_answer_feed').select('*').eq('question_id',params.id).order('created_at',{ascending:true})]);setUserId(auth.user?.id??null);if(qv)setQ({...qv,topic_name:locale==='bn'?((qv as any).topic_name_bn??(qv as any).topic_name_en):((qv as any).topic_name_en??(qv as any).topic_name_bn)} as Question);setAnswers((av??[]) as Answer[]);},[params.id])
 useEffect(()=>{void load()},[load])
 async function answer(){if(!userId||!body.trim())return;setBusy(true);const s=createClient();const {error}=await s.from('fenix_answers').insert({question_id:params.id,author_id:userId,body:body.trim()});if(error)setMessage(locale==='bn'?'উত্তর দেওয়া যায়নি।':'Could not publish answer.');else{setBody('');await load()}setBusy(false)}
 async function vote(id:string){if(!userId){setMessage(locale==='bn'?'Vote দিতে Login করুন।':'Sign in to vote.');return}const s=createClient();const {data:old}=await s.from('fenix_content_votes').select('value').eq('user_id',userId).eq('content_type','answer').eq('content_id',id).maybeSingle();if(old)await s.from('fenix_content_votes').delete().eq('user_id',userId).eq('content_type','answer').eq('content_id',id);else await s.from('fenix_content_votes').insert({user_id:userId,content_type:'answer',content_id:id,value:1});await load()}
 if(!q)return <main className="min-h-dvh"><Navbar/><section className="mx-auto max-w-3xl px-4 py-10"><Link href="/feed" className="font-bold">← {locale==='bn'?'Feed':'Feed'}</Link><p className="mt-8 text-sm text-[var(--fx-muted)]">{locale==='bn'?'Question পাওয়া যায়নি।':'Question not found.'}</p></section></main>
 return <main className="min-h-dvh"><Navbar/><section className="mx-auto max-w-3xl px-4 pb-28 pt-7 sm:px-6"><Link href="/feed" className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-[var(--fx-border)] px-3.5 text-xs font-bold"><ArrowLeft size={16}/> Feed</Link><article className="mt-5 rounded-[2rem] border border-[var(--fx-border)] bg-[var(--fx-surface)] p-5 sm:p-7"><div className="flex items-center gap-3">{q.author_avatar_url?<img src={q.author_avatar_url} alt="" className="h-10 w-10 rounded-full object-cover"/>:<UserCircle size={40} className="opacity-40"/>}<div><p className="text-sm font-bold">{q.author_name||q.author_username||'FeniX user'}</p><time className="text-[11px] text-[var(--fx-muted)]">{new Date(q.created_at).toLocaleString(locale==='bn'?'bn-BD':'en-BD')}</time></div></div><h1 className="mt-5 text-2xl font-black leading-9 sm:text-4xl">{q.title}</h1>{q.topic_name&&<p className="mt-2 text-xs font-bold text-[var(--fx-primary-strong)]">{q.topic_name}</p>}<p className="mt-5 whitespace-pre-wrap text-sm leading-8">{q.body}</p><div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>void navigator.share?.({title:q.title,url:location.href})} className="rounded-xl border border-[var(--fx-border)] px-3 py-2 text-xs font-bold"><ShareNetwork size={15} className="mr-1 inline"/>Share</button><button className="rounded-xl border border-[var(--fx-border)] px-3 py-2 text-xs font-bold"><BookmarkSimple size={15} className="mr-1 inline"/>Save</button></div></article>
 <section className="mt-5"><h2 className="text-xl font-black">{locale==='bn'?'উত্তর':'Answers'} ({answers.length})</h2>{userId?<div className="mt-3 rounded-[1.7rem] border border-[var(--fx-border)] bg-[var(--fx-surface)] p-4"><textarea value={body} onChange={e=>setBody(e.target.value)} rows={5} maxLength={20000} placeholder={locale==='bn'?'আপনার উত্তর লিখুন…':'Write your answer…'} className="w-full rounded-xl border border-[var(--fx-border)] bg-transparent p-3 text-sm leading-7"/><button disabled={busy||!body.trim()} onClick={()=>void answer()} className="mt-2 ml-auto block rounded-xl bg-[var(--fx-primary-strong)] px-4 py-2.5 text-xs font-bold text-white disabled:opacity-40"><PaperPlaneRight size={15} className="mr-1 inline"/> {locale==='bn'?'উত্তর দিন':'Answer'}</button></div>:<Link href={`/login?next=/feed/question/${params.id}`} className="mt-3 block rounded-2xl bg-[var(--fx-primary-soft)] p-4 text-center text-sm font-bold text-[var(--fx-primary-strong)]">{locale==='bn'?'উত্তর দিতে Login করুন':'Sign in to answer'}</Link>}
 <div className="mt-4 space-y-3">{answers.map(a=><article key={a.id} className="rounded-[1.7rem] border border-[var(--fx-border)] bg-[var(--fx-surface)] p-5"><div className="flex items-center gap-3">{a.author_avatar_url?<img src={a.author_avatar_url} alt="" className="h-9 w-9 rounded-full object-cover"/>:<UserCircle size={36} className="opacity-40"/>}<div><p className="text-sm font-bold">{a.author_name||a.author_username||'FeniX user'}</p><time className="text-[11px] text-[var(--fx-muted)]">{new Date(a.created_at).toLocaleString(locale==='bn'?'bn-BD':'en-BD')}</time></div></div><p className="mt-3 whitespace-pre-wrap text-sm leading-7">{a.body}</p><button onClick={()=>void vote(a.id)} className="mt-3 rounded-xl border border-[var(--fx-border)] px-3 py-2 text-xs font-bold"><ThumbsUp size={15} className="mr-1 inline"/>Helpful</button></article>)}</div></section>
 </section></main>
}
