export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: { Row: { id: string; full_name: string | null; role: 'admin' | 'vendor' | 'customer'; phone: string | null; created_at: string; updated_at: string }; Insert: { id: string; full_name?: string | null; role?: 'admin' | 'vendor' | 'customer'; phone?: string | null; created_at?: string; updated_at?: string }; Update: { id?: string; full_name?: string | null; role?: 'admin' | 'vendor' | 'customer'; phone?: string | null; created_at?: string; updated_at?: string }; Relationships: [] }
      businesses: { Row: { id: string; owner_id: string | null; name: string; updated_at: string; title_bn: string | null; title_en: string | null; description: string | null; category: string | null; feni_brain_embedding: number[] | null; created_at: string }; Insert: { id?: string; owner_id?: string | null; name: string; updated_at?: string; title_bn?: string | null; title_en?: string | null; description?: string | null; category?: string | null; feni_brain_embedding?: number[] | null; created_at?: string }; Update: { id?: string; owner_id?: string | null; name?: string; updated_at?: string; title_bn?: string | null; title_en?: string | null; description?: string | null; category?: string | null; feni_brain_embedding?: number[] | null; created_at?: string }; Relationships: [] }
      product_categories: { Row: { id: string; name_bn: string; name_en: string; slug: string; description_bn: string | null; description_en: string | null; parent_id: string | null; image_url: string | null; is_active: boolean; sort_order: number; created_at: string; updated_at: string }; Insert: { id?: string; name_bn: string; name_en: string; slug: string; description_bn?: string | null; description_en?: string | null; parent_id?: string | null; image_url?: string | null; is_active?: boolean; sort_order?: number; created_at?: string; updated_at?: string }; Update: { id?: string; name_bn?: string; name_en?: string; slug?: string; description_bn?: string | null; description_en?: string | null; parent_id?: string | null; image_url?: string | null; is_active?: boolean; sort_order?: number; created_at?: string; updated_at?: string }; Relationships: [] }
      vendor_profiles: { Row: { id: string; user_id: string; business_id: string | null; display_name: string; display_name_bn: string | null; display_name_en: string | null; description_bn: string | null; description_en: string | null; phone: string | null; status: 'pending' | 'approved' | 'rejected' | 'suspended'; is_verified: boolean; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; business_id?: string | null; display_name: string; display_name_bn?: string | null; display_name_en?: string | null; description_bn?: string | null; description_en?: string | null; phone?: string | null; status?: 'pending' | 'approved' | 'rejected' | 'suspended'; is_verified?: boolean; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; business_id?: string | null; display_name?: string; display_name_bn?: string | null; display_name_en?: string | null; description_bn?: string | null; description_en?: string | null; phone?: string | null; status?: 'pending' | 'approved' | 'rejected' | 'suspended'; is_verified?: boolean; created_at?: string; updated_at?: string }; Relationships: [] }
      products: { Row: { id: string; vendor_id: string; business_id: string | null; category_id: string | null; name_bn: string; name_en: string; slug: string; description_bn: string | null; description_en: string | null; sku: string | null; price: number; compare_at_price: number | null; currency: string; status: 'draft' | 'pending' | 'published' | 'paused' | 'archived'; is_active: boolean; is_featured: boolean; allow_guest_purchase: boolean; created_at: string; updated_at: string }; Insert: { id?: string; vendor_id: string; business_id?: string | null; category_id?: string | null; name_bn: string; name_en: string; slug: string; description_bn?: string | null; description_en?: string | null; sku?: string | null; price: number; compare_at_price?: number | null; currency?: string; status?: 'draft' | 'pending' | 'published' | 'paused' | 'archived'; is_active?: boolean; is_featured?: boolean; allow_guest_purchase?: boolean; created_at?: string; updated_at?: string }; Update: { id?: string; vendor_id?: string; business_id?: string | null; category_id?: string | null; name_bn?: string; name_en?: string; slug?: string; description_bn?: string | null; description_en?: string | null; sku?: string | null; price?: number; compare_at_price?: number | null; currency?: string; status?: 'draft' | 'pending' | 'published' | 'paused' | 'archived'; is_active?: boolean; is_featured?: boolean; allow_guest_purchase?: boolean; created_at?: string; updated_at?: string }; Relationships: [] }
      product_images: { Row: { id: string; product_id: string; storage_bucket: string; storage_path: string; alt_text_bn: string | null; alt_text_en: string | null; sort_order: number; is_primary: boolean; created_at: string }; Insert: { id?: string; product_id: string; storage_bucket: string; storage_path: string; alt_text_bn?: string | null; alt_text_en?: string | null; sort_order?: number; is_primary?: boolean; created_at?: string }; Update: { id?: string; product_id?: string; storage_bucket?: string; storage_path?: string; alt_text_bn?: string | null; alt_text_en?: string | null; sort_order?: number; is_primary?: boolean; created_at?: string }; Relationships: [] }
      inventory: { Row: { id: string; product_id: string; quantity: number; reserved_quantity: number; low_stock_threshold: number; updated_at: string }; Insert: { id?: string; product_id: string; quantity?: number; reserved_quantity?: number; low_stock_threshold?: number; updated_at?: string }; Update: { id?: string; product_id?: string; quantity?: number; reserved_quantity?: number; low_stock_threshold?: number; updated_at?: string }; Relationships: [] }
      orders: { Row: { id: string; order_number: string; customer_id: string | null; guest_name: string | null; guest_phone: string | null; guest_email: string | null; status: 'pending' | 'confirmed' | 'processing' | 'ready' | 'shipped' | 'delivered' | 'cancelled' | 'returned'; payment_status: 'unpaid' | 'pending' | 'paid' | 'failed' | 'refunded' | 'partially_refunded'; payment_method: 'cash_on_delivery' | 'online' | 'manual'; currency: string; subtotal: number; delivery_fee: number; discount_amount: number; total_amount: number; shipping_name: string; shipping_phone: string; shipping_address: string; shipping_area: string | null; shipping_upazila: string | null; shipping_district: string | null; customer_note: string | null; created_at: string; updated_at: string }; Insert: { id?: string; order_number?: string; customer_id?: string | null; guest_name?: string | null; guest_phone?: string | null; guest_email?: string | null; status?: 'pending' | 'confirmed' | 'processing' | 'ready' | 'shipped' | 'delivered' | 'cancelled' | 'returned'; payment_status?: 'unpaid' | 'pending' | 'paid' | 'failed' | 'refunded' | 'partially_refunded'; payment_method?: 'cash_on_delivery' | 'online' | 'manual'; currency?: string; subtotal?: number; delivery_fee?: number; discount_amount?: number; total_amount?: number; shipping_name: string; shipping_phone: string; shipping_address: string; shipping_area?: string | null; shipping_upazila?: string | null; shipping_district?: string | null; customer_note?: string | null; created_at?: string; updated_at?: string }; Update: { id?: string; order_number?: string; customer_id?: string | null; guest_name?: string | null; guest_phone?: string | null; guest_email?: string | null; status?: 'pending' | 'confirmed' | 'processing' | 'ready' | 'shipped' | 'delivered' | 'cancelled' | 'returned'; payment_status?: 'unpaid' | 'pending' | 'paid' | 'failed' | 'refunded' | 'partially_refunded'; payment_method?: 'cash_on_delivery' | 'online' | 'manual'; currency?: string; subtotal?: number; delivery_fee?: number; discount_amount?: number; total_amount?: number; shipping_name?: string; shipping_phone?: string; shipping_address?: string; shipping_area?: string | null; shipping_upazila?: string | null; shipping_district?: string | null; customer_note?: string | null; created_at?: string; updated_at?: string }; Relationships: [] }
      order_items: { Row: { id: string; order_id: string; product_id: string | null; vendor_id: string | null; product_name: string; product_sku: string | null; quantity: number; unit_price: number; discount_amount: number; line_total: number; created_at: string }; Insert: { id?: string; order_id: string; product_id?: string | null; vendor_id?: string | null; product_name: string; product_sku?: string | null; quantity: number; unit_price: number; discount_amount?: number; line_total: number; created_at?: string }; Update: { id?: string; order_id?: string; product_id?: string | null; vendor_id?: string | null; product_name?: string; product_sku?: string | null; quantity?: number; unit_price?: number; discount_amount?: number; line_total?: number; created_at?: string }; Relationships: [] }
    }
    Views: { [_ in never]: never }
    Functions: {
      create_commerce_order: { Args: { p_items: Json; p_customer_id?: string | null; p_guest_name?: string | null; p_guest_phone?: string | null; p_guest_email?: string | null; p_shipping_name?: string | null; p_shipping_phone?: string | null; p_shipping_address?: string | null; p_shipping_area?: string | null; p_shipping_upazila?: string | null; p_shipping_district?: string | null; p_customer_note?: string | null }; Returns: { order_id: string; order_number: string; total_amount: number }[] }
      generate_commerce_order_number: { Args: Record<string, never>; Returns: string }
      set_vendor_product_inventory: { Args: { p_product_id: string; p_quantity: number; p_low_stock_threshold?: number }; Returns: boolean }
      publish_vendor_product: { Args: { p_product_id: string }; Returns: boolean }
      archive_vendor_product: { Args: { p_product_id: string }; Returns: boolean }
      match_businesses: { Args: { query_embedding: number[]; match_threshold: number; match_count: number }; Returns: { id: string; name: string; description: string | null; similarity: number }[] }
      save_business_embedding: { Args: { p_business_id: string; p_embedding: number[] }; Returns: boolean }
    }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}

export type Profile = Database['public']['Tables']['profiles']['Row']
export type ProfileInsert = Database['public']['Tables']['profiles']['Insert']
export type ProfileUpdate = Database['public']['Tables']['profiles']['Update']
export type Business = Database['public']['Tables']['businesses']['Row']
export type BusinessInsert = Database['public']['Tables']['businesses']['Insert']
export type BusinessUpdate = Database['public']['Tables']['businesses']['Update']
export type ProductCategory = Database['public']['Tables']['product_categories']['Row']
export type ProductCategoryInsert = Database['public']['Tables']['product_categories']['Insert']
export type ProductCategoryUpdate = Database['public']['Tables']['product_categories']['Update']
export type VendorProfile = Database['public']['Tables']['vendor_profiles']['Row']
export type VendorProfileInsert = Database['public']['Tables']['vendor_profiles']['Insert']
export type VendorProfileUpdate = Database['public']['Tables']['vendor_profiles']['Update']
export type Product = Database['public']['Tables']['products']['Row']
export type ProductInsert = Database['public']['Tables']['products']['Insert']
export type ProductUpdate = Database['public']['Tables']['products']['Update']
export type ProductImage = Database['public']['Tables']['product_images']['Row']
export type ProductImageInsert = Database['public']['Tables']['product_images']['Insert']
export type ProductImageUpdate = Database['public']['Tables']['product_images']['Update']
export type Inventory = Database['public']['Tables']['inventory']['Row']
export type InventoryInsert = Database['public']['Tables']['inventory']['Insert']
export type InventoryUpdate = Database['public']['Tables']['inventory']['Update']
export type Order = Database['public']['Tables']['orders']['Row']
export type OrderInsert = Database['public']['Tables']['orders']['Insert']
export type OrderUpdate = Database['public']['Tables']['orders']['Update']
export type OrderItem = Database['public']['Tables']['order_items']['Row']
export type OrderItemInsert = Database['public']['Tables']['order_items']['Insert']
export type OrderItemUpdate = Database['public']['Tables']['order_items']['Update']
