export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

type VendorStatus = 'pending' | 'approved' | 'rejected' | 'suspended'
type ProductStatus = 'draft' | 'pending' | 'published' | 'paused' | 'archived'
type OrderStatus = 'pending' | 'confirmed' | 'processing' | 'ready' | 'shipped' | 'delivered' | 'cancelled' | 'returned'
type PaymentStatus = 'unpaid' | 'pending' | 'paid' | 'failed' | 'refunded' | 'partially_refunded'

export type Database = {
  public: {
    Tables: {
      profiles: { Row: { id: string; full_name: string | null; role: string; phone: string | null; created_at: string; updated_at: string }; Insert: { id: string; full_name?: string | null; role?: string; phone?: string | null; created_at?: string; updated_at?: string }; Update: { id?: string; full_name?: string | null; role?: string; phone?: string | null; created_at?: string; updated_at?: string }; Relationships: [] }
      businesses: { Row: { id: string; owner_id: string | null; name: string; updated_at: string; title_bn: string | null; title_en: string | null; description: string | null; category: string | null; feni_brain_embedding: number[] | null; created_at: string }; Insert: { id?: string; owner_id?: string | null; name: string; updated_at?: string; title_bn?: string | null; title_en?: string | null; description?: string | null; category?: string | null; feni_brain_embedding?: number[] | null; created_at?: string }; Update: { id?: string; owner_id?: string | null; name?: string; updated_at?: string; title_bn?: string | null; title_en?: string | null; description?: string | null; category?: string | null; feni_brain_embedding?: number[] | null; created_at?: string }; Relationships: [] }
      business_directory_profiles: { Row: { business_id: string; slug: string | null; tagline_bn: string | null; tagline_en: string | null; about_bn: string | null; about_en: string | null; business_type: string | null; listing_status: 'published' | 'unlisted' | 'suspended'; owner_claimed: boolean; verification_level: 'unverified' | 'owner_claimed' | 'identity_reviewed' | 'business_reviewed' | 'fenix_verified'; phone_verified: boolean; location_verified: boolean; last_verified_at: string | null; created_at: string; updated_at: string }; Insert: { business_id: string; slug?: string | null; tagline_bn?: string | null; tagline_en?: string | null; about_bn?: string | null; about_en?: string | null; business_type?: string | null; listing_status?: 'published' | 'unlisted' | 'suspended'; owner_claimed?: boolean; verification_level?: 'unverified' | 'owner_claimed' | 'identity_reviewed' | 'business_reviewed' | 'fenix_verified'; phone_verified?: boolean; location_verified?: boolean; last_verified_at?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['business_directory_profiles']['Insert']> }
      business_directory_locations: { Row: { business_id: string; district: string; upazila: string | null; area: string | null; market: string | null; address: string | null; postal_code: string | null; latitude: number | null; longitude: number | null; map_label: string | null; location_source: string | null; is_public: boolean; created_at: string; updated_at: string }; Insert: { business_id: string; district?: string; upazila?: string | null; area?: string | null; market?: string | null; address?: string | null; postal_code?: string | null; latitude?: number | null; longitude?: number | null; map_label?: string | null; location_source?: string | null; is_public?: boolean; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['business_directory_locations']['Insert']> }
      business_directory_contacts: { Row: { business_id: string; phone: string | null; whatsapp: string | null; website_url: string | null; facebook_url: string | null; is_phone_public: boolean; is_whatsapp_public: boolean; is_website_public: boolean; created_at: string; updated_at: string }; Insert: { business_id: string; phone?: string | null; whatsapp?: string | null; website_url?: string | null; facebook_url?: string | null; is_phone_public?: boolean; is_whatsapp_public?: boolean; is_website_public?: boolean; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['business_directory_contacts']['Insert']> }
      business_directory_aliases: { Row: { id: string; business_id: string; alias: string; language_code: 'bn' | 'en' | 'banglish' | 'local'; created_at: string }; Insert: { id?: string; business_id: string; alias: string; language_code?: 'bn' | 'en' | 'banglish' | 'local'; created_at?: string }; Update: Partial<Database['public']['Tables']['business_directory_aliases']['Insert']> }
      product_categories: { Row: { id: string; name_bn: string | null; name_en: string | null; slug: string; description_bn: string | null; description_en: string | null; parent_id: string | null; image_url: string | null; is_active: boolean; sort_order: number; created_at: string; updated_at: string }; Insert: { id?: string; name_bn?: string | null; name_en?: string | null; slug: string; description_bn?: string | null; description_en?: string | null; parent_id?: string | null; image_url?: string | null; is_active?: boolean; sort_order?: number; created_at?: string; updated_at?: string }; Update: { id?: string; name_bn?: string | null; name_en?: string | null; slug?: string; description_bn?: string | null; description_en?: string | null; parent_id?: string | null; image_url?: string | null; is_active?: boolean; sort_order?: number; created_at?: string; updated_at?: string }; Relationships: [] }
      vendor_profiles: { Row: { id: string; user_id: string; business_id: string | null; display_name: string; display_name_bn: string | null; display_name_en: string | null; description_bn: string | null; description_en: string | null; phone: string | null; shop_slug: string | null; status: VendorStatus; is_verified: boolean; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; business_id?: string | null; display_name: string; display_name_bn?: string | null; display_name_en?: string | null; description_bn?: string | null; description_en?: string | null; phone?: string | null; shop_slug?: string | null; status?: VendorStatus; is_verified?: boolean; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; business_id?: string | null; display_name?: string; display_name_bn?: string | null; display_name_en?: string | null; description_bn?: string | null; description_en?: string | null; phone?: string | null; shop_slug?: string | null; status?: VendorStatus; is_verified?: boolean; created_at?: string; updated_at?: string }; Relationships: [] }
      products: { Row: { id: string; vendor_id: string; business_id: string | null; category_id: string | null; name_bn: string; name_en: string; slug: string; description_bn: string | null; description_en: string | null; sku: string | null; price: number; compare_at_price: number | null; currency: string; status: ProductStatus; is_active: boolean; is_featured: boolean; allow_guest_purchase: boolean; created_at: string; updated_at: string }; Insert: { id?: string; vendor_id: string; business_id?: string | null; category_id?: string | null; name_bn: string; name_en: string; slug: string; description_bn?: string | null; description_en?: string | null; sku?: string | null; price: number; compare_at_price?: number | null; currency?: string; status?: ProductStatus; is_active?: boolean; is_featured?: boolean; allow_guest_purchase?: boolean; created_at?: string; updated_at?: string }; Update: { id?: string; vendor_id?: string; business_id?: string | null; category_id?: string | null; name_bn?: string; name_en?: string; slug?: string; description_bn?: string | null; description_en?: string | null; sku?: string | null; price?: number; compare_at_price?: number | null; currency?: string; status?: ProductStatus; is_active?: boolean; is_featured?: boolean; allow_guest_purchase?: boolean; created_at?: string; updated_at?: string }; Relationships: [] }
      product_images: { Row: { id: string; product_id: string; storage_bucket: string; storage_path: string; alt_text_bn: string | null; alt_text_en: string | null; sort_order: number; is_primary: boolean; created_at: string }; Insert: { id?: string; product_id: string; storage_bucket: string; storage_path: string; alt_text_bn?: string | null; alt_text_en?: string | null; sort_order?: number; is_primary?: boolean; created_at?: string }; Update: { id?: string; product_id?: string; storage_bucket?: string; storage_path?: string; alt_text_bn?: string | null; alt_text_en?: string | null; sort_order?: number; is_primary?: boolean; created_at?: string }; Relationships: [] }
      inventory: { Row: { id: string; product_id: string; quantity: number; reserved_quantity: number; low_stock_threshold: number; updated_at: string }; Insert: { id?: string; product_id: string; quantity?: number; reserved_quantity?: number; low_stock_threshold?: number; updated_at?: string }; Update: { id?: string; product_id?: string; quantity?: number; reserved_quantity?: number; low_stock_threshold?: number; updated_at?: string }; Relationships: [] }
      orders: { Row: { id: string; order_number: string; customer_id: string | null; guest_name: string | null; guest_phone: string | null; guest_email: string | null; status: OrderStatus; payment_status: PaymentStatus; payment_method: 'cash_on_delivery' | 'online' | 'manual'; currency: string; subtotal: number; delivery_fee: number; discount_amount: number; total_amount: number; shipping_name: string; shipping_phone: string; shipping_address: string; shipping_area: string | null; shipping_upazila: string | null; shipping_district: string | null; customer_note: string | null; created_at: string; updated_at: string }; Insert: { id?: string; order_number?: string; customer_id?: string | null; guest_name?: string | null; guest_phone?: string | null; guest_email?: string | null; status?: OrderStatus; payment_status?: PaymentStatus; payment_method?: 'cash_on_delivery' | 'online' | 'manual'; currency?: string; subtotal?: number; delivery_fee?: number; discount_amount?: number; total_amount?: number; shipping_name: string; shipping_phone: string; shipping_address: string; shipping_area?: string | null; shipping_upazila?: string | null; shipping_district?: string | null; customer_note?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['orders']['Insert']> }
      order_items: { Row: { id: string; order_id: string; product_id: string | null; vendor_id: string | null; product_name: string; product_sku: string | null; quantity: number; unit_price: number; discount_amount: number; line_total: number; created_at: string }; Insert: { id?: string; order_id: string; product_id?: string | null; vendor_id?: string | null; product_name: string; product_sku?: string | null; quantity: number; unit_price: number; discount_amount?: number; line_total: number; created_at?: string }; Update: Partial<Database['public']['Tables']['order_items']['Insert']> }
      commerce_delivery_rules: { Row: { id: string; district: string | null; upazila: string | null; fee: number; free_shipping_minimum: number | null; is_active: boolean; sort_order: number; created_at: string; updated_at: string }; Insert: { id?: string; district?: string | null; upazila?: string | null; fee?: number; free_shipping_minimum?: number | null; is_active?: boolean; sort_order?: number; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['commerce_delivery_rules']['Insert']> }
      commerce_order_vendor_status: { Row: { id: string; order_id: string; vendor_id: string; status: string; inventory_finalized: boolean; created_at: string; updated_at: string }; Insert: { id?: string; order_id: string; vendor_id: string; status?: string; inventory_finalized?: boolean; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['commerce_order_vendor_status']['Insert']> }
      product_reviews: { Row: { id: string; product_id: string; order_id: string; customer_id: string; rating: number; title: string | null; body: string | null; status: 'pending' | 'published' | 'rejected'; seller_response: string | null; seller_responded_at: string | null; created_at: string; updated_at: string }; Insert: { id?: string; product_id: string; order_id: string; customer_id: string; rating: number; title?: string | null; body?: string | null; status?: 'pending' | 'published' | 'rejected'; seller_response?: string | null; seller_responded_at?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['product_reviews']['Insert']> }

      investment_profiles: { Row: { user_id: string; investor_type: string; bio: string | null; min_budget: number; max_budget: number; preferred_sectors: string[]; preferred_upazilas: string[]; risk_preference: string; horizon_months: number | null; shariah_preference: string; verification_status: string; verification_note: string | null; verified_at: string | null; verified_by: string | null; created_at: string; updated_at: string }; Insert: { user_id: string; investor_type?: string; bio?: string | null; min_budget?: number; max_budget?: number; preferred_sectors?: string[]; preferred_upazilas?: string[]; risk_preference?: string; horizon_months?: number | null; shariah_preference?: string; verification_status?: string; verification_note?: string | null; verified_at?: string | null; verified_by?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['investment_profiles']['Insert']> }
      investment_opportunities: { Row: { id: string; owner_id: string; business_id: string | null; title_bn: string; title_en: string; description_bn: string; description_en: string; category: string; district: string; upazila: string | null; location_details: string | null; target_amount: number; min_investment: number; raised_amount: number; offer_type: string; ownership_percentage: number | null; expected_return_pct: number | null; expected_term_months: number | null; risk_level: string; shariah_preference: string; risk_disclosure: string | null; funding_deadline: string | null; status: string; verification_status: string; verification_note: string | null; verified_at: string | null; verified_by: string | null; created_at: string; updated_at: string }; Insert: { id?: string; owner_id: string; business_id?: string | null; title_bn: string; title_en: string; description_bn: string; description_en: string; category: string; district?: string; upazila?: string | null; location_details?: string | null; target_amount: number; min_investment: number; raised_amount?: number; offer_type?: string; ownership_percentage?: number | null; expected_return_pct?: number | null; expected_term_months?: number | null; risk_level?: string; shariah_preference?: string; risk_disclosure?: string | null; funding_deadline?: string | null; status?: string; verification_status?: string; verification_note?: string | null; verified_at?: string | null; verified_by?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['investment_opportunities']['Insert']> }
      investment_documents: { Row: { id: string; opportunity_id: string; owner_id: string; document_type: string; title: string; storage_bucket: string; storage_path: string; visibility: string; status: string; review_note: string | null; reviewed_by: string | null; reviewed_at: string | null; created_at: string; updated_at: string }; Insert: { id?: string; opportunity_id: string; owner_id: string; document_type: string; title: string; storage_bucket?: string; storage_path: string; visibility?: string; status?: string; review_note?: string | null; reviewed_by?: string | null; reviewed_at?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['investment_documents']['Insert']> }
      investment_interests: { Row: { id: string; opportunity_id: string; investor_id: string; offered_amount: number; message: string | null; status: string; owner_note: string | null; created_at: string; updated_at: string }; Insert: { id?: string; opportunity_id: string; investor_id: string; offered_amount: number; message?: string | null; status?: string; owner_note?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['investment_interests']['Insert']> }
      investment_deals: { Row: { id: string; opportunity_id: string; investor_id: string; agreed_amount: number; ownership_percentage: number | null; structure: string; status: string; terms_note: string | null; investor_confirmed_at: string | null; owner_confirmed_at: string | null; funded_at: string | null; started_at: string | null; completed_at: string | null; created_at: string; updated_at: string }; Insert: { id?: string; opportunity_id: string; investor_id: string; agreed_amount: number; ownership_percentage?: number | null; structure?: string; status?: string; terms_note?: string | null; investor_confirmed_at?: string | null; owner_confirmed_at?: string | null; funded_at?: string | null; started_at?: string | null; completed_at?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['investment_deals']['Insert']> }
      investment_updates: { Row: { id: string; opportunity_id: string; author_id: string; title: string; body: string; period_label: string | null; revenue_actual: number | null; customers_actual: number | null; risk_note: string | null; profit_actual: number | null; return_actual_pct: number | null; created_at: string; updated_at: string }; Insert: { id?: string; opportunity_id: string; author_id: string; title: string; body: string; period_label?: string | null; revenue_actual?: number | null; customers_actual?: number | null; risk_note?: string | null; profit_actual?: number | null; return_actual_pct?: number | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['investment_updates']['Insert']> }
      investment_reports: { Row: { id: string; opportunity_id: string; reporter_id: string; reason: string; details: string; status: string; resolution_note: string | null; resolved_by: string | null; resolved_at: string | null; created_at: string; updated_at: string }; Insert: { id?: string; opportunity_id: string; reporter_id: string; reason: string; details: string; status?: string; resolution_note?: string | null; resolved_by?: string | null; resolved_at?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['investment_reports']['Insert']> }
      investment_messages: { Row: { id: string; opportunity_id: string; deal_id: string | null; sender_id: string; recipient_id: string; body: string; created_at: string; read_at: string | null }; Insert: { id?: string; opportunity_id: string; deal_id?: string | null; sender_id: string; recipient_id: string; body: string; created_at?: string; read_at?: string | null }; Update: Partial<Database['public']['Tables']['investment_messages']['Insert']> }
      investment_audit_logs: { Row: { id: string; actor_id: string | null; opportunity_id: string | null; entity_type: string; entity_id: string | null; action: string; details: Json; created_at: string }; Insert: never; Update: never }
      fenix_brain_query_terms: { Row: { id: string; intent_key: string; term: string; language_code: string; weight: number; created_at: string }; Insert: { id?: string; intent_key: string; term: string; language_code?: string; weight?: number; created_at?: string }; Update: { id?: string; intent_key?: string; term?: string; language_code?: string; weight?: number; created_at?: string }; Relationships: [] }
      fenix_brain_locations: { Row: { id: string; parent_id: string | null; level: string; name_bn: string; name_en: string | null; slug: string; official_code: string | null; metadata: Json; is_active: boolean; created_at: string; updated_at: string }; Insert: { id?: string; parent_id?: string | null; level: string; name_bn: string; name_en?: string | null; slug: string; official_code?: string | null; metadata?: Json; is_active?: boolean; created_at?: string; updated_at?: string }; Update: { id?: string; parent_id?: string | null; level?: string; name_bn?: string; name_en?: string | null; slug?: string; official_code?: string | null; metadata?: Json; is_active?: boolean; created_at?: string; updated_at?: string }; Relationships: [] }
      commerce_return_requests: { Row: { id: string; order_id: string; order_item_id: string; customer_id: string; reason: string; details: string | null; status: 'requested' | 'approved' | 'rejected' | 'received' | 'refunded' | 'cancelled'; resolution_note: string | null; refund_amount: number | null; created_at: string; updated_at: string }; Insert: { id?: string; order_id: string; order_item_id: string; customer_id: string; reason: string; details?: string | null; status?: 'requested' | 'approved' | 'rejected' | 'received' | 'refunded' | 'cancelled'; resolution_note?: string | null; refund_amount?: number | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['commerce_return_requests']['Insert']> }
    }
    Views: {
      commerce_public_products: { Row: { id: string; vendor_id: string; category_id: string | null; name_bn: string; name_en: string; slug: string; description_bn: string | null; description_en: string | null; sku: string | null; price: number; compare_at_price: number | null; currency: string; allow_guest_purchase: boolean; is_featured: boolean; created_at: string; vendor_display_name: string; vendor_display_name_bn: string | null; vendor_display_name_en: string | null; vendor_is_verified: boolean; shop_slug: string | null; image_id: string | null; image_bucket: string | null; image_path: string | null; image_alt_bn: string | null; image_alt_en: string | null } }
    }
    Functions: {

      submit_investment_opportunity: { Args: { p_opportunity_id: string }; Returns: boolean }
      owner_progress_investment_deal: { Args: { p_deal_id: string; p_status: string; p_agreed_amount?: number | null; p_ownership_percentage?: number | null; p_terms_note?: string | null }; Returns: boolean }
      investor_confirm_investment_deal: { Args: { p_deal_id: string }; Returns: boolean }
      owner_confirm_investment_deal: { Args: { p_deal_id: string }; Returns: boolean }
      mark_investment_message_read: { Args: { p_message_id: string }; Returns: boolean }
      owner_update_investment_interest: { Args: { p_interest_id: string; p_status: string; p_owner_note?: string | null }; Returns: boolean }
      match_investment_opportunities: { Args: { p_limit?: number | null }; Returns: { opportunity_id: string; title_bn: string; title_en: string; category: string; district: string; upazila: string | null; target_amount: number; min_investment: number; raised_amount: number; risk_level: string; verification_status: string; match_score: number; match_reasons: string[] }[] }
      create_commerce_order: { Args: { p_items: Json; p_customer_id?: string | null; p_guest_name?: string | null; p_guest_phone?: string | null; p_guest_email?: string | null; p_shipping_name?: string | null; p_shipping_phone?: string | null; p_shipping_address?: string | null; p_shipping_area?: string | null; p_shipping_upazila?: string | null; p_shipping_district?: string | null; p_customer_note?: string | null }; Returns: { order_id: string; order_number: string; total_amount: number }[] }
      generate_commerce_order_number: { Args: Record<string, never>; Returns: string }
      set_vendor_product_inventory: { Args: { p_product_id: string; p_quantity: number; p_low_stock_threshold?: number }; Returns: boolean }
      publish_vendor_product: { Args: { p_product_id: string }; Returns: boolean }
      archive_vendor_product: { Args: { p_product_id: string }; Returns: boolean }
      update_vendor_profile: { Args: { p_display_name: string; p_display_name_bn?: string | null; p_display_name_en?: string | null; p_description_bn?: string | null; p_description_en?: string | null; p_phone?: string | null; p_shop_slug?: string | null }; Returns: boolean }
      update_vendor_product: { Args: { p_product_id: string; p_name_bn: string; p_name_en: string; p_slug: string; p_description_bn?: string | null; p_description_en?: string | null; p_sku?: string | null; p_price?: number; p_compare_at_price?: number | null; p_category_id?: string | null; p_allow_guest_purchase?: boolean }; Returns: boolean }
      set_product_primary_image: { Args: { p_image_id: string }; Returns: boolean }
      get_public_vendor_shop: { Args: { p_slug: string }; Returns: { id: string; shop_slug: string; display_name: string; display_name_bn: string | null; display_name_en: string | null; description_bn: string | null; description_en: string | null; is_verified: boolean; business_id: string | null }[] }
      calculate_commerce_delivery_fee: { Args: { p_district: string | null; p_upazila: string | null; p_subtotal: number }; Returns: number }
      set_vendor_order_status: { Args: { p_order_id: string; p_status: string }; Returns: boolean }
      create_product_review: { Args: { p_product_id: string; p_rating: number; p_title?: string | null; p_body?: string | null }; Returns: string }
      seller_reply_to_product_review: { Args: { p_review_id: string; p_response: string }; Returns: boolean }
      create_commerce_return_request: { Args: { p_order_item_id: string; p_reason: string; p_details?: string | null }; Returns: string }
      set_commerce_return_status: { Args: { p_request_id: string; p_status: string; p_resolution_note?: string | null; p_refund_amount?: number | null }; Returns: boolean }
      is_fenix_admin: { Args: Record<string, never>; Returns: boolean }
      admin_set_vendor_status: { Args: { p_vendor_id: string; p_status: string; p_is_verified?: boolean }; Returns: boolean }
      admin_upsert_delivery_rule: { Args: { p_rule_id?: string | null; p_district?: string | null; p_upazila?: string | null; p_fee?: number; p_free_shipping_minimum?: number | null; p_is_active?: boolean; p_sort_order?: number }; Returns: string }
      admin_delete_delivery_rule: { Args: { p_rule_id: string }; Returns: boolean }
      admin_set_review_status: { Args: { p_review_id: string; p_status: string }; Returns: boolean }
      admin_set_order_payment_status: { Args: { p_order_id: string; p_payment_status: string }; Returns: boolean }
      search_feni_brain_facts: { Args: { query_text: string; match_count?: number }; Returns: { id: string; document_id: string; subject_key: string; name_bn: string; name_en: string | null; value_number: number | null; value_text: string | null; value_unit: string | null; content: string; similarity: number; source_id: string; source_title: string; source_url: string | null; trust_tier: number; document_title: string }[] }
      keyword_feni_brain_chunks: { Args: { query_text: string; match_count?: number }; Returns: { id: string; document_id: string; content: string; similarity: number; source_id: string; source_title: string; source_url: string | null; trust_tier: number; document_title: string }[] }
      match_feni_brain_chunks: { Args: { query_embedding: number[]; match_threshold: number; match_count: number }; Returns: { id: string; document_id: string; content: string; similarity: number; source_id: string; source_title: string; source_url: string | null; trust_tier: number; document_title: string }[] }
      search_feni_brain_locations: { Args: { query_text: string; match_count?: number }; Returns: { id: string; level: string; name_bn: string; name_en: string | null; slug: string; alias: string; match_type: string }[] }
      search_directory_businesses: { Args: { p_query?: string | null; p_category?: string | null; p_upazila?: string | null; p_limit?: number | null; p_offset?: number | null }; Returns: { id: string; name: string; title_bn: string | null; title_en: string | null; description: string | null; category: string | null; created_at: string; updated_at: string; tagline_bn: string | null; tagline_en: string | null; listing_status: string; verification_level: string; owner_claimed: boolean; phone_verified: boolean; location_verified: boolean; district: string | null; upazila: string | null; area: string | null; market: string | null; address: string | null; latitude: number | null; longitude: number | null; map_label: string | null; phone: string | null; whatsapp: string | null; website_url: string | null; facebook_url: string | null; product_count: number; has_investment: boolean }[] }
      list_directory_categories: { Args: Record<string, never>; Returns: { category: string | null; business_count: number }[] }
      list_directory_upazilas: { Args: Record<string, never>; Returns: { upazila: string | null; business_count: number }[] }
      match_businesses: { Args: { query_embedding: number[]; match_threshold: number; match_count: number }; Returns: { id: string; name: string; description: string | null; similarity: number }[] }
      save_business_embedding: { Args: { p_business_id: string; p_embedding: number[] }; Returns: boolean }
    }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}

export type BusinessDirectoryProfile = Database['public']['Tables']['business_directory_profiles']['Row']
export type BusinessDirectoryLocation = Database['public']['Tables']['business_directory_locations']['Row']
export type BusinessDirectoryContact = Database['public']['Tables']['business_directory_contacts']['Row']
export type BusinessDirectoryAlias = Database['public']['Tables']['business_directory_aliases']['Row']
export type Profile = Database['public']['Tables']['profiles']['Row']
export type ProfileInsert = Database['public']['Tables']['profiles']['Insert']
export type ProfileUpdate = Database['public']['Tables']['profiles']['Update']
export type Business = Database['public']['Tables']['businesses']['Row']
export type BusinessInsert = Database['public']['Tables']['businesses']['Insert']
export type BusinessUpdate = Database['public']['Tables']['businesses']['Update']
export type ProductCategory = Database['public']['Tables']['product_categories']['Row']
export type ProductCategoryInsert = Database['public']['Tables']['product_categories']['Insert']
export type ProductCategoryUpdate = Database['public']['Tables']['product_categories']['Update']
export type VendorProfile = Database['public']['Tables']['vendor_profiles']['Row']
export type VendorProfileInsert = Database['public']['Tables']['vendor_profiles']['Insert']
export type VendorProfileUpdate = Database['public']['Tables']['vendor_profiles']['Update']
export type Product = Database['public']['Tables']['products']['Row']
export type ProductInsert = Database['public']['Tables']['products']['Insert']
export type ProductUpdate = Database['public']['Tables']['products']['Update']
export type ProductImage = Database['public']['Tables']['product_images']['Row']
export type ProductImageInsert = Database['public']['Tables']['product_images']['Insert']
export type ProductImageUpdate = Database['public']['Tables']['product_images']['Update']
export type Inventory = Database['public']['Tables']['inventory']['Row']
export type InventoryInsert = Database['public']['Tables']['inventory']['Insert']
export type InventoryUpdate = Database['public']['Tables']['inventory']['Update']
export type Order = Database['public']['Tables']['orders']['Row']
export type OrderInsert = Database['public']['Tables']['orders']['Insert']
export type OrderUpdate = Database['public']['Tables']['orders']['Update']
export type OrderItem = Database['public']['Tables']['order_items']['Row']
export type OrderItemInsert = Database['public']['Tables']['order_items']['Insert']
export type OrderItemUpdate = Database['public']['Tables']['order_items']['Update']
export type ProductReview = Database['public']['Tables']['product_reviews']['Row']
export type ProductReviewInsert = Database['public']['Tables']['product_reviews']['Insert']
export type ProductReviewUpdate = Database['public']['Tables']['product_reviews']['Update']
export type CommerceReturnRequest = Database['public']['Tables']['commerce_return_requests']['Row']
export type CommerceReturnRequestInsert = Database['public']['Tables']['commerce_return_requests']['Insert']
export type CommerceReturnRequestUpdate = Database['public']['Tables']['commerce_return_requests']['Update']

export type InvestmentProfile = Database['public']['Tables']['investment_profiles']['Row']
export type InvestmentProfileInsert = Database['public']['Tables']['investment_profiles']['Insert']
export type InvestmentProfileUpdate = Database['public']['Tables']['investment_profiles']['Update']
export type InvestmentOpportunity = Database['public']['Tables']['investment_opportunities']['Row']
export type InvestmentOpportunityInsert = Database['public']['Tables']['investment_opportunities']['Insert']
export type InvestmentOpportunityUpdate = Database['public']['Tables']['investment_opportunities']['Update']
export type InvestmentDocument = Database['public']['Tables']['investment_documents']['Row']
export type InvestmentInterest = Database['public']['Tables']['investment_interests']['Row']
export type InvestmentDeal = Database['public']['Tables']['investment_deals']['Row']
export type InvestmentUpdate = Database['public']['Tables']['investment_updates']['Row']
export type InvestmentReport = Database['public']['Tables']['investment_reports']['Row']

export type InvestmentMessage = Database['public']['Tables']['investment_messages']['Row']
