'use client'

import { useState } from 'react'
import { ImageSquare, Trash, Star, UploadSimple } from '@phosphor-icons/react'
import { createClient } from '@/utils/supabase/client'
import { optimizeImageFile } from '@/lib/media/image-upload'

type ImageRow={id:string;storage_bucket:string;storage_path:string;alt_text_bn:string|null;alt_text_en:string|null;sort_order:number;is_primary:boolean}
export default function ProductImageManager({productId,vendorId,images,onChange}:{productId:string;vendorId:string;images:ImageRow[];onChange:(images:ImageRow[])=>void}){const[busy,setBusy]=useState(false);const[error,setError]=useState('')
async function upload(files:FileList|null){if(!files?.length)return;setBusy(true);setError('');const added:ImageRow[]=[];try{const s=createClient();for(const file of Array.from(files).slice(0,5)){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw new Error('Only JPG, PNG or WebP images up to 5MB are allowed.');const optimized=await optimizeImageFile(file,{maxDimension:1600});const extension=optimized.mimeType==='image/webp'?'webp':'jpg';const path=vendorId+'/'+productId+'/'+crypto.randomUUID()+'.'+extension;const{error:e}=await s.storage.from('product-images').upload(path,optimized.file,{contentType:optimized.mimeType,upsert:false});if(e)throw e;const{data:row,error:re}=await s.from('product_images').insert({product_id:productId,storage_bucket:'product-images',storage_path:path,sort_order:images.length+added.length,is_primary:images.length===0&&added.length===0}).select('id,storage_bucket,storage_path,alt_text_bn,alt_text_en,sort_order,is_primary').single();if(re||!row)throw re??new Error('Image metadata failed');added.push(row as ImageRow)}if(added.length)onChange([...images,...added])}catch(e){setError(e instanceof Error?e.message:'Image upload failed.')}finally{setBusy(false)}}
async function remove(image:ImageRow){setBusy(true);setError('');const s=createClient();const{error:e}=await s.storage.from('product-images').remove([image.storage_path]);if(e){setError('Image delete করা যায়নি।');setBusy(false);return}const{error:re}=await s.from('product_images').delete().eq('id',image.id);if(re){setError('Image record delete করা যায়নি।');setBusy(false);return}onChange(images.filter(x=>x.id!==image.id));setBusy(false)}
async function primary(image:ImageRow){setBusy(true);setError('');const s=createClient();const{error:e}=await s.rpc('set_product_primary_image',{p_image_id:image.id});if(e)setError('Primary image set করা যায়নি।');else onChange(images.map(x=>({...x,is_primary:x.id===image.id})));setBusy(false)}
return <div className="rounded-[2rem] border border-[#0b1736]/10 bg-white/75 p-6 dark:border-white/10 dark:bg-white/[.045]"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 font-black"><ImageSquare size={20}/> Product images</h2><p className="mt-1 text-xs opacity-50">JPG, PNG, WebP · source up to 5MB · auto-optimized below 200KB · up to 5</p></div><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl bg-[#008080] px-4 py-3 text-sm font-bold text-white"><UploadSimple size={17}/>{busy?'Working…':'Upload images'}<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy} onChange={e=>void upload(e.target.files)} className="hidden"/></label></div>{error&&<p className="mt-4 rounded-xl bg-red-500/5 p-3 text-xs text-red-600">{error}</p>}<div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{images.map(image=>{const url=`${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/${image.storage_bucket}/${image.storage_path}`;return <div key={image.id} className="overflow-hidden rounded-2xl border border-[#0b1736]/10 dark:border-white/10">{/* Intentional public storage image URL. */}
  {/* eslint-disable-next-line @next/next/no-img-element */}
  <img src={url} alt={image.alt_text_en||image.alt_text_bn||'Product image'} className="aspect-square w-full object-cover"/><div className="flex items-center justify-between gap-2 p-3"><button type="button" disabled={busy||image.is_primary} onClick={()=>void primary(image)} className="inline-flex items-center gap-1.5 rounded-lg px-2 py-1.5 text-xs font-bold disabled:opacity-40"><Star size={14} weight={image.is_primary?'fill':'regular'}/> {image.is_primary?'Primary':'Set primary'}</button><button type="button" disabled={busy} onClick={()=>void remove(image)} className="rounded-lg p-2 text-red-600 disabled:opacity-40"><Trash size={16}/></button></div></div>})}</div>{!images.length&&<div className="mt-5 rounded-2xl border border-dashed border-[#0b1736]/15 p-10 text-center text-sm opacity-50 dark:border-white/10">No product images yet.</div>}</div>}
